<?xml version="1.0"?>
<robot>  


<gazebo>
  <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
    <updateRate>100.0</updateRate>
    <robotNamespace>/</robotNamespace>
    <leftFrontJoint>left_wheel_joint</leftFrontJoint>
    <rightFrontJoint>right_wheel_joint</rightFrontJoint>
    <leftRearJoint>left1_wheel_joint</leftRearJoint>
    <rightRearJoint>right1_wheel_joint</rightRearJoint>
    <wheelSeparation>${wheel_separation}</wheelSeparation>
    <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
    <robotBaseFrame>base_link</robotBaseFrame>
    <odometryTopic>/mobile_robot/odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <torque>20</torque>
    <commandTopic>/mobile_robot/cmd_vel</commandTopic>
    <broadcastTF>false</broadcastTF>
  </plugin>
</gazebo>




  <!--Gazebo Hokuyo Laser Plugin-->
  <gazebo reference="sensor_laser">
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>20</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>1440</samples>
            <resolution>1</resolution>
            <min_angle>-1.5</min_angle>
            <max_angle>1.5</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/laser_scan/scan</topicName>
        <frameName>/sensor_laser</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
<!--  
  <xacro:xtion_pro_live name="rgbd_camera" parent="base_link">
    <origin xyz="0.15 0.0 0.8" rpy="0 ${75.0 * deg_to_rad} 0"/>
    <origin xyz="0 0 0" rpy="${-90.0 * deg_to_rad} 0 ${-90.0 * deg_to_rad}"/>
  </xacro:xtion_pro_live>
-->
    
     <!--Gazebo Camera Plugin-->
   <gazebo reference="camera">
    <sensor type="camera" name="camera">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>1280</width>
          <height>760</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo> 
  
<!-- Light source -->

<gazebo reference="light1_link">
    <light type="spot" name="light1">
        <pose>${camera_origin_x} ${camera_origin_y+0.05} ${camera_origin_z} 1.57 0 -1.57</pose>
        <attenuation>
          <range>20</range>
          <linear>0.10</linear>
        </attenuation>

      <diffuse>0.7 0.7 0.7 0</diffuse>
      <specular>1 1 1 0</specular>
      <direction>1 1 1</direction>
      <spot>
      	<inner_angle>1</inner_angle>
      	<outer_angle>1</outer_angle>
       	<falloff>1</falloff>     	
      </spot>

    </light>
   

  <selfCollide>false</selfCollide>
</gazebo>  
    

<gazebo reference="light2_link">

    <light type="spot" name="light2">
        <pose>${camera_origin_x} ${camera_origin_y-0.05} ${camera_origin_z} 1.57 0 -1.57</pose>   
        <attenuation>
          <range>20</range>
          <linear>0.10</linear>
        </attenuation>

      <diffuse>0.7 0.7 0.7 0</diffuse>
      <specular>1 1 1 0</specular>
      <direction>1 1 1</direction>
      <spot>
      	<inner_angle>1</inner_angle>
      	<outer_angle>1</outer_angle>
       	<falloff>1</falloff>     	
      </spot>

    </light>
    

  <selfCollide>false</selfCollide>
</gazebo>      

    
<!-- Color reference -->

<gazebo reference="base_link">
  <material>Gazebo/Orange</material>
</gazebo>

<gazebo reference="left_wheel">
  <material>Gazebo/White</material>
</gazebo>
<gazebo reference="right_wheel">
  <material>Gazebo/White</material>
</gazebo>
<gazebo reference="left1_wheel">
  <material>Gazebo/White</material>
</gazebo>
<gazebo reference="right1_wheel">
  <material>Gazebo/White</material>
</gazebo>

<gazebo reference="camera">
  <material>Gazebo/Red</material>
</gazebo>

<gazebo reference="sensor_laser">
  <material>Gazebo/Blue</material>
</gazebo>

<gazebo reference="light1_link">
  <material>Gazebo/Green</material>
</gazebo>

<gazebo reference="light2_link">
  <material>Gazebo/Green</material>
</gazebo>








 
</robot>
